name: fp_pbb_kel6
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Instagram Sans
      fonts:
        - asset: assets/fonts/Instagram Sans.ttf
        - asset: assets/fonts/Instagram Sans Bold.ttf
          weight: 700
        
    - family: Instagram Headline
      fonts: 
        - asset: assets/fonts/Instagram Sans Headline.otf
    
    - family: San Fransisco
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
  assets:
    - assets/
