name: fp_pbb_kel6
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.0
  http: ^1.1.0

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  http_parser: ^4.1.2
  mime: ^2.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Instagram Sans
      fonts:
        - asset: assets/fonts/Instagram Sans.ttf
        - asset: assets/fonts/Instagram Sans Bold.ttf
          weight: 700
        
    - family: Instagram Headline
      fonts: 
        - asset: assets/fonts/Instagram Sans Headline.otf
    
    - family: San Fransisco
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
  assets:
    - assets/
    - assets/images/

flutter_native_splash:
  android: true
  color: "#000000"

  android_12:
    image: assets/images/splashlogo.png
    branding: assets/images/branding.png
    color: "#000000"

flutter_launcher_icons:
  android: true

  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/iggradient.png"
  adaptive_icon_foreground: "assets/images/icon.png"