// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMfyBNQV-2T6epUZalCK8itfIxwV_5wh8',
    appId: '1:954981334471:web:27cb9ee99d4ea996ae2de2',
    messagingSenderId: '954981334471',
    projectId: 'fp-ppb-6757a',
    authDomain: 'fp-ppb-6757a.firebaseapp.com',
    storageBucket: 'fp-ppb-6757a.firebasestorage.app',
    measurementId: 'G-6RG4QXM1DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdlClLgqEFtcj1nmZZplfc31hWieF1pQ',
    appId: '1:954981334471:android:a0b8880a26d70419ae2de2',
    messagingSenderId: '954981334471',
    projectId: 'fp-ppb-6757a',
    storageBucket: 'fp-ppb-6757a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvlNIpLiRulqAuFoml1HQ0B4Qe-LzwqC8',
    appId: '1:954981334471:ios:85122ed1c1c99ee5ae2de2',
    messagingSenderId: '954981334471',
    projectId: 'fp-ppb-6757a',
    storageBucket: 'fp-ppb-6757a.firebasestorage.app',
    iosBundleId: 'com.example.fpPbbKel6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvlNIpLiRulqAuFoml1HQ0B4Qe-LzwqC8',
    appId: '1:954981334471:ios:85122ed1c1c99ee5ae2de2',
    messagingSenderId: '954981334471',
    projectId: 'fp-ppb-6757a',
    storageBucket: 'fp-ppb-6757a.firebasestorage.app',
    iosBundleId: 'com.example.fpPbbKel6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMfyBNQV-2T6epUZalCK8itfIxwV_5wh8',
    appId: '1:954981334471:web:19b9b65ad8dee915ae2de2',
    messagingSenderId: '954981334471',
    projectId: 'fp-ppb-6757a',
    authDomain: 'fp-ppb-6757a.firebaseapp.com',
    storageBucket: 'fp-ppb-6757a.firebasestorage.app',
    measurementId: 'G-W58VBN5YD5',
  );
}
